// <auto-generated />
namespace EvaluadorDeRestaurante.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedpropertyinmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedpropertyinmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202106280436543_changed property in model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
